spring:
  application:
    name: delivery
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            value:
              default:
                type: com.codingeass.delivery.dto.OrderDelivery

